/**
 * 
 */
package tutorial.symreg;

import net.sf.jclec.exprtree.fun.Argument;

/**
 * @author Rafael Barbudo Lunar
 *
 */
public class Const1 extends Argument<Double> 
{
	//////////////////////////////////////////////////////////////////////
	// -------------------------------------------- Serialization constant
	//////////////////////////////////////////////////////////////////////

	/** Generated by Eclipse */
	
	private static final long serialVersionUID = 5070008596298358184L;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////
	
	/**
	 * Empty constructor
	 */
	
	public Const1() {
		super(Double.class, 1);
	}

	public boolean equals(int argindex)
	{
		return this.argindex == argindex;
	}	
	
	public String toString()
	{
		return "C1";
	}
	
}
